###
GET http://127.0.0.1:8080/entity/users

###
GET http://127.0.0.1:8080/entity/users/1

###
POST http://127.0.0.1:8080/entity/users
Content-Type: application/json

{
  "id":"userTest",
  "pwd": "passTest",
  "name": "유니콘",
  "enrollDate": "2025-03-20"
}

###
PUT http://127.0.0.1:8080/entity/users/4
Content-Type: application/json

{
    "id":"modifyTest",
    "pwd": "modifyTest",
    "name": "유니콘 진화"
}

###
DELETE http://127.0.0.1:8080/entity/users/4

